In [18]:
import numpy as np

In [19]:
py_list = [1, 2, 3, 4, 5]
print(py_list)

[1, 2, 3, 4, 5]


In [20]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)

[1 2 3 4 5]


In [21]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
c = np.arange(1, 11)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
d = np.arange(1, 21).reshape(4, 5)
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [24]:
d = np.zeros(5)
print(d)

[0. 0. 0. 0. 0.]


In [25]:
d_2 = np.zeros((2,3))
print(d_2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
import numpy as np

In [27]:
a = np.array([1, 2, 3, 4, 5])

print(a[0])
print(a[2])

print(a[-1])
print(a[-3])

1
3
5
3


In [28]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(b[0, 0])
print(b[1, 2])
print(b[-1, -1])

1
6
9


In [29]:
c = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(c[2:7])
print(c[:4])
print(c[6:])

[2 3 4 5 6]
[0 1 2 3]
[6 7 8 9]


In [30]:
print(c[1:8:2])

[1 3 5 7]


In [31]:
tow_dimensional = np.array(


  [
      [10, 20, 30],
      [40, 50, 60]
      [70, 80, 90]
  ]  
)

<>:6: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:6: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/var/folders/kb/tk0p38cx0h1d_dtvmbtqb1g00000gn/T/ipykernel_10919/1996786709.py:6: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [40, 50, 60]
/var/folders/kb/tk0p38cx0h1d_dtvmbtqb1g00000gn/T/ipykernel_10919/1996786709.py:6: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [40, 50, 60]
/var/folders/kb/tk0p38cx0h1d_dtvmbtqb1g00000gn/T/ipykernel_10919/1996786709.py:6: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [40, 50, 60]


TypeError: list indices must be integers or slices, not tuple

In [ ]:
print("二次元並列のスライス")

二次元並列のスライス


In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2])
b = np.array([4, 5, 6])
c = a + b
print(c)

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [ ]:
d = np.array([1, 2], [3, 4])
e = np.array([[5, 6], [7, 8]])
f = d + e
print(f)

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [ ]:
a = np.array

In [ ]:
a = np.array([1 ,2 ,3])
b = np.array([10, 20 ,30])

In [32]:
b = np.array([10])

In [34]:
a = np.array([[1 ,2 ,3], [4, 5, 6]])
b = np.array([10, 20 ,30])

In [35]:
a + b

array([[11, 22, 33],
       [14, 25, 36]])

In [37]:
a = np.array([[1, 2], [3, 4]])
scalar = 5
result = a + scalar

result

array([[6, 7],
       [8, 9]])

In [40]:
try:
    print( 1 / 0)
except ZeroDivisionError:
    print('0以外を入力しろ')

print(111)

0以外を入力しろ
111
