In [20]:
import numpy as np

In [21]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [22]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
b = np.arange(10)
print(b[::2])


[0 2 4 6 8]


In [24]:
c = np.arange(5, 16, 2)
print(c)

[ 5  7  9 11 13 15]


In [25]:
d = np.zeros((3, 4))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
e = np.ones((2, 3), dtype=np.float64)
print(e)

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a * b
print(result)

[ 4 10 18]


In [28]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
shape = c.shape
print(shape)

(2, 2, 2)


In [ ]:
d = np.arange(1, 21).reshape(4, 5)
second_row = d[1]
print(second_row)

In [29]:


e = np.array([10, 20, 30, 40, 50])
result = e / 10
print(result)

[1. 2. 3. 4. 5.]
